# Generated by Django 2.2.1 on 2021-05-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='post_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user_comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user_post',
        ),
    ]
